# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "howto_disroot_lan" do |howto_disroot_lan|
	howto_disroot_lan.vm.box="debian/stretch64"
	howto_disroot_lan.vm.hostname = 'howto.disroot.lan'
	howto_disroot_lan.vm.box_url = "debian/stretch64"

	howto_disroot_lan.vm.synced_folder "provision/", "/vagrant/provision/"
#	howto_disroot_lan.vm.synced_folder "../pages/", "/var/www/howto.disroot.lan/user/pages", owner: "www-data", group: "www-data"

	howto_disroot_lan.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "192.168.33.11"
	howto_disroot_lan.vm.network "forwarded_port", guest: 443, host: 4443, host_ip: "192.168.33.11"
	howto_disroot_lan.vm.network "private_network", ip: "192.168.33.11"

	howto_disroot_lan.vm.provision :shell, path: "bootstrap.sh"

	howto_disroot_lan.vm.synced_folder "../pages/", "/var/www/pages", owner: "www-data", group: "www-data"


end
end
